### PR TITLE
Fix typo in custom_model_data and fix Vault

### PR DESCRIPTION
**Pull request by ajh123**
## Info
This fixes a typo in `custom_model_data`. The git history may show my previous fix (hence the one extra file change).

Also before this Vault was loaded once the plugin's `onLoad` was called, this will cause issues because the database hasn't been connected yet. Now Vault gets loaded after the `loadFiles` in the `onEnable` so the plugin can initialise the database first.

## Details

I want this to be added because creating corporations (and Vault support) doesn't work.

### OS
OS: Win / Mac / Linux / Win 

#### MC Builds
- [ ] Tested on Latest Spigot Version
- [x] Tested on Latest Paper / Purpur Version

#### JDK Builds
Tested on:
- [X] JDK Version 17 (I assume it is)
- [ ] JDK Version 16
- [ ] JDK Version 11
- [ ] JDK Version 1.8

## Demonstration
Screenshots or any other info, if you please.

### CODE REVIEW

**Comment by GamerCoder215** [comment]
Vault needs to be called in `onLoad` in order for proper registering and economy conversion to happen (I originally put it in `onEnable` and had users reporting errors with conversion). File Loading can probably be moved to `onLoad` but I'd have to test it.

**Comment by ajh123** [comment]
For me loading vault in the `onLoad` cause the following error 
```
[13:14:56] [Server thread/INFO] [Novaconomy/]: Loading Novaconomy v1.8.1
[13:14:56] [Server thread/INFO] [Novaconomy/]: Vault Found! Hooking...
[13:14:56] [Server thread/ERROR] [Novaconomy/]: NullPointerException
[13:14:56] [Server thread/ERROR] [Novaconomy/]: -----------
[13:14:56] [Server thread/ERROR] [Novaconomy/]: Cannot invoke "java.sql.Connection.createStatement()" because "db" is null
[13:14:56] [Server thread/ERROR] [Novaconomy/]: us.teaminceptus.novaconomy.api.economy.Economy.checkTable(Economy.java:584)
[13:14:56] [Server thread/ERROR] [Novaconomy/]: us.teaminceptus.novaconomy.api.economy.Economy.getEconomies(Economy.java:351)
[13:14:56] [Server thread/ERROR] [Novaconomy/]: us.teaminceptus.novaconomy.vault.VaultRegistry.reloadVault(VaultRegistry.java:20)
[13:14:56] [Server thread/ERROR] [Novaconomy/]: us.teaminceptus.novaconomy.Novaconomy.onLoad(Novaconomy.java:947)
[13:14:56] [Server thread/ERROR] [Novaconomy/]: TRANSFORMER/arclight@1.20.1-1.0.0-053d747/org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServerMixin.java:438)
[13:14:56] [Server thread/ERROR] [Novaconomy/]: TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.handler$zdg000$arclight$loadPlugins(DedicatedServerMixin.java:627)
[13:14:56] [Server thread/ERROR] [Novaconomy/]: TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServerMixin.java:156)
[13:14:56] [Server thread/ERROR] [Novaconomy/]: TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2028)
[13:14:56] [Server thread/ERROR] [Novaconomy/]: TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251)
```

I can try having the `loadFiles` in the `onLoad` if you want.

**Comment by GamerCoder215** [comment]
That'd work. The error is that when using SQL the database hasn't been loaded yet. `loadFiles` may need some tweaking because it uses the input of `#getDataFolder` but I'm not sure.

**Comment by ajh123** [comment]
Look like this is working now. Just needed to defer the start of some of the `BukkitRunable`s into the `onEnable`, with Vault and `loadFiles` in the `onLoad`.

**Comment by ajh123** [comment]
Also `getDataFolder` looks fine because Bukkit initialises this when they call the constructor for our plugin.

**Review by GamerCoder215 — APPROVED** [review]
LGTM!

**Pull request merged**
